name: Build LaTeX document

on:
  push:
    branches:
      - main
    paths:
      - 'texFiles/**/*.tex'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags

    - name: Install TeX Live
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-xetex texlive-fonts-recommended texlive-plain-generic

    - name: Get changed LaTeX file
      id: latex-file
      run: |
        # Get the list of changed .tex files in the texFiles directory
        FILES=$(git diff --name-only HEAD^ -- texFiles/*.tex)
        echo "Changed LaTeX file(s): $FILES"
        
        # Check if there's exactly one LaTeX file changed
        if [ $(echo "$FILES" | wc -l) -ne 1 ]; then
          echo "Error: There should be exactly one LaTeX file changed."
          exit 1
        fi

        # Get the filename without extension and the directory
        FILENAME=$(basename $FILES .tex)
        DIRNAME=$(dirname $FILES)
        
        # Set the file name and directory as output variables
        echo "::set-output name=filename::$FILENAME"
        echo "::set-output name=dirname::$DIRNAME"

    - name: Build LaTeX document with xelatex
      run: |
        # Use the filename and directory from the previous step
        cd ${{ steps.latex-file.outputs.dirname }}
        xelatex ${{ steps.latex-file.outputs.filename }}.tex

    - name: Move PDF to output directory
      run: |
        mkdir -p pdfFiles
        mv ${{ steps.latex-file.outputs.dirname }}/${{ steps.latex-file.outputs.filename }}.pdf pdfFiles/

    - name: Commit and push PDF
      env:
         GH_PAT: ${{ secrets.GH_PAT }}
      run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add pdfFiles/${{ steps.latex-file.outputs.filename }}.pdf
            git commit -m "Add generated PDF for ${{ steps.latex-file.outputs.filename }}.tex"
            git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git HEAD:main